apiVersion: apps/v1
kind: Deployment
metadata:
  name: openaiops-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openaiops-ui
  template:
    metadata:
      labels:
        app: openaiops-ui
    spec:
      containers:
        - name: openaiops-ui
          image: openaiops-ui:latest
          ports:
            - containerPort: 8050
          env:
            - name: API_URL
              value: "http://openaiops-api:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: openaiops-ui
spec:
  type: NodePort
  selector:
    app: openaiops-ui
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
      nodePort: 30050
